project:
  type: website

execute: 
  freeze: auto

website:
  title: "Euro Area Inflation"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Table"
        href: inflation-table.qmd
    tools:
      - icon: github
        href: https://github.com/econMaett/ea-inflation
  
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



