name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main

  # Cron schedule to run on the 16th day of every month at 10:00 AM ET
  schedule:
    - cron: '0 10 16 * *'

env:
  TZ: "Germany/Berlin"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.2"
      
      # Step 3: Install Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: LATEST

      # Step 4: Install packages with Posit Package Manager
      - name: Install R packages
        run: |
          Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
          Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"
          
      # Step 5: Render the Quarto file and publish to GitHub Pages
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 6: Commit data files
      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}